<?php

namespace App\DataFixtures;

use App\Entity\Line;
use App\Entity\Station;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;

class StationsFixtures extends Fixture implements DependentFixtureInterface
{
    public function load(ObjectManager $manager): void
    {
        $stations = $this->getStationsData();

        foreach ($stations as $lineRef => $lineStations) {
            /** @var Line $line */
            $line = $this->getReference($lineRef, Line::class);

            foreach ($lineStations as $stationData) {
                $station = new Station();
                $station->setName($stationData['name']);
                $station->setLine($line);
                $station->setPosition($stationData['position']);

                // Définir la branche si elle existe
                if (isset($stationData['branch'])) {
                    $station->setBranch($stationData['branch']);
                }

                $manager->persist($station);
            }
        }

        $manager->flush();
    }

    private function getStationsData(): array
    {
        return [
            LineFixtures::LINE_1_REFERENCE => array_map(fn($name, $pos) => ['name' => $name, 'position' => $pos], [
                'La Défense',
                'Esplanade de La Défense',
                'Pont de Neuilly',
                'Les Sablons',
                'Porte Maillot',
                'Argentine',
                'Charles de Gaulle - Étoile',
                'George V',
                'Franklin D. Roosevelt',
                'Champs-Élysées - Clemenceau',
                'Concorde',
                'Tuileries',
                'Palais Royal - Musée du Louvre',
                'Louvre - Rivoli',
                'Châtelet',
                'Hôtel de Ville',
                'Saint-Paul',
                'Bastille',
                'Gare de Lyon',
                'Reuilly - Diderot',
                'Nation',
                'Porte de Vincennes',
                'Saint-Mandé',
                'Bérault',
                'Château de Vincennes',
            ], range(1, 25)),

            LineFixtures::LINE_2_REFERENCE => array_map(fn($name, $pos) => ['name' => $name, 'position' => $pos], [
                'Porte Dauphine',
                'Victor Hugo',
                'Charles de Gaulle - Étoile',
                'Ternes',
                'Courcelles',
                'Monceau',
                'Villiers',
                'Rome',
                'Place de Clichy',
                'Blanche',
                'Pigalle',
                'Anvers',
                'Barbès - Rochechouart',
                'La Chapelle',
                'Stalingrad',
                'Jaurès',
                'Colonel Fabien',
                'Belleville',
                'Couronnes',
                'Ménilmontant',
                'Père Lachaise',
                'Philippe Auguste',
                'Alexandre Dumas',
                'Avron',
                'Nation',
            ], range(1, 25)),

            LineFixtures::LINE_3_REFERENCE => array_map(fn($name, $pos) => ['name' => $name, 'position' => $pos], [
                'Pont de Levallois - Bécon',
                'Anatole France',
                'Louise Michel',
                'Porte de Champerret',
                'Pereire',
                'Wagram',
                'Malesherbes',
                'Villiers',
                'Europe',
                'Saint-Lazare',
                'Havre - Caumartin',
                'Opéra',
                'Quatre-Septembre',
                'Bourse',
                'Sentier',
                'Réaumur - Sébastopol',
                'Arts et Métiers',
                'Temple',
                'République',
                'Parmentier',
                'Rue Saint-Maur',
                'Père Lachaise',
                'Gambetta',
                'Porte de Bagnolet',
                'Gallieni',
            ], range(1, 25)),

            LineFixtures::LINE_3BIS_REFERENCE => array_map(fn($name, $pos) => ['name' => $name, 'position' => $pos], [
                'Porte des Lilas',
                'Saint-Fargeau',
                'Pelleport',
                'Gambetta',
            ], range(1, 4)),

            LineFixtures::LINE_4_REFERENCE => array_map(fn($name, $pos) => ['name' => $name, 'position' => $pos], [
                'Porte de Clignancourt',
                'Simplon',
                'Marcadet - Poissonniers',
                'Château Rouge',
                'Barbès - Rochechouart',
                'Gare du Nord',
                'Gare de l\'Est',
                'Château d\'Eau',
                'Strasbourg - Saint-Denis',
                'Réaumur - Sébastopol',
                'Étienne Marcel',
                'Les Halles',
                'Châtelet',
                'Cité',
                'Saint-Michel',
                'Odéon',
                'Saint-Germain-des-Prés',
                'Saint-Sulpice',
                'Saint-Placide',
                'Montparnasse - Bienvenüe',
                'Vavin',
                'Raspail',
                'Denfert-Rochereau',
                'Mouton-Duvernet',
                'Alésia',
                'Porte d\'Orléans',
                'Mairie de Montrouge',
                'Barbara',
                'Bagneux - Lucie Aubrac'
            ], range(1, 29)),

            LineFixtures::LINE_5_REFERENCE => array_map(fn($name, $pos) => ['name' => $name, 'position' => $pos], [
                'Bobigny - Pablo Picasso',
                'Bobigny - Pantin - Raymond Queneau',
                'Église de Pantin',
                'Hoche',
                'Porte de Pantin',
                'Ourcq',
                'Laumière',
                'Jaurès',
                'Stalingrad',
                'Gare du Nord',
                'Gare de l\'Est',
                'Jacques Bonsergent',
                'République',
                'Oberkampf',
                'Richard-Lenoir',
                'Bréguet - Sabin',
                'Bastille',
                'Quai de la Rapée',
                'Gare d\'Austerlitz',
                'Saint-Marcel',
                'Campo-Formio',
                'Place d\'Italie',
            ], range(1, 22)),

            LineFixtures::LINE_6_REFERENCE => array_map(fn($name, $pos) => ['name' => $name, 'position' => $pos], [
                'Charles de Gaulle - Étoile',
                'Kléber',
                'Boissière',
                'Trocadéro',
                'Passy',
                'Bir-Hakeim',
                'Dupleix',
                'La Motte-Picquet - Grenelle',
                'Cambronne',
                'Sèvres - Lecourbe',
                'Pasteur',
                'Montparnasse - Bienvenüe',
                'Edgar Quinet',
                'Raspail',
                'Denfert-Rochereau',
                'Saint-Jacques',
                'Glacière',
                'Corvisart',
                'Place d\'Italie',
                'Nationale',
                'Chevaleret',
                'Quai de la Gare',
                'Bercy',
                'Dugommier',
                'Daumesnil',
                'Bel-Air',
                'Picpus',
                'Nation',
            ], range(1, 28)),

            LineFixtures::LINE_7_REFERENCE => [
                // Tronc commun Nord
                ['name' => 'La Courneuve - 8 Mai 1945', 'position' => 1],
                ['name' => 'Fort d\'Aubervilliers', 'position' => 2],
                ['name' => 'Aubervilliers - Pantin - Quatre Chemins', 'position' => 3],
                ['name' => 'Porte de la Villette', 'position' => 4],
                ['name' => 'Corentin Cariou', 'position' => 5],
                ['name' => 'Crimée', 'position' => 6],
                ['name' => 'Riquet', 'position' => 7],
                ['name' => 'Stalingrad', 'position' => 8],
                ['name' => 'Louis Blanc', 'position' => 9],
                ['name' => 'Château-Landon', 'position' => 10],
                ['name' => 'Gare de l\'Est', 'position' => 11],
                ['name' => 'Poissonnière', 'position' => 12],
                ['name' => 'Cadet', 'position' => 13],
                ['name' => 'Le Peletier', 'position' => 14],
                ['name' => 'Chaussée d\'Antin - La Fayette', 'position' => 15],
                ['name' => 'Opéra', 'position' => 16],
                ['name' => 'Pyramides', 'position' => 17],
                ['name' => 'Palais Royal - Musée du Louvre', 'position' => 18],
                ['name' => 'Pont Neuf', 'position' => 19],
                ['name' => 'Châtelet', 'position' => 20],
                ['name' => 'Pont Marie', 'position' => 21],
                ['name' => 'Sully - Morland', 'position' => 22],
                ['name' => 'Jussieu', 'position' => 23],
                ['name' => 'Place Monge', 'position' => 24],
                ['name' => 'Censier - Daubenton', 'position' => 25],
                ['name' => 'Les Gobelins', 'position' => 26],
                ['name' => 'Place d\'Italie', 'position' => 27],
                ['name' => 'Tolbiac', 'position' => 28],

                // Point de fourche
                ['name' => 'Maison Blanche', 'position' => 29, 'branch' => 'fork'],

                // Branche Villejuif (à gauche)
                ['name' => 'Le Kremlin-Bicêtre', 'position' => 30, 'branch' => 'villejuif'],
                ['name' => 'Villejuif - Léo Lagrange', 'position' => 31, 'branch' => 'villejuif'],
                ['name' => 'Villejuif - Paul Vaillant-Couturier', 'position' => 32, 'branch' => 'villejuif'],
                ['name' => 'Villejuif - Louis Aragon', 'position' => 33, 'branch' => 'villejuif'],

                // Branche Ivry (à droite)
                ['name' => 'Porte d\'Italie', 'position' => 30, 'branch' => 'ivry'],
                ['name' => 'Porte de Choisy', 'position' => 31, 'branch' => 'ivry'],
                ['name' => 'Porte d\'Ivry', 'position' => 32, 'branch' => 'ivry'],
                ['name' => 'Pierre et Marie Curie', 'position' => 33, 'branch' => 'ivry'],
                ['name' => 'Mairie d\'Ivry', 'position' => 34, 'branch' => 'ivry'],
            ],

            LineFixtures::LINE_7BIS_REFERENCE => [
                ['name' => 'Louis Blanc', 'position' => 1],
                ['name' => 'Jaurès', 'position' => 2],
                ['name' => 'Bolivar', 'position' => 3],
                ['name' => 'Buttes Chaumont', 'position' => 4],
                ['name' => 'Botzaris', 'position' => 5],
                ['name' => 'Place des Fêtes', 'position' => 6, 'branch' => 'direction'],
                ['name' => 'Danube', 'position' => 7, 'branch' => 'retour'],
                ['name' => 'Pré-Saint-Gervais', 'position' => 8],
            ],

            LineFixtures::LINE_8_REFERENCE => array_map(fn($name, $pos) => ['name' => $name, 'position' => $pos], [
                'Balard',
                'Lourmel',
                'Boucicaut',
                'Félix Faure',
                'Commerce',
                'La Motte-Picquet - Grenelle',
                'École Militaire',
                'La Tour-Maubourg',
                'Invalides',
                'Concorde',
                'Madeleine',
                'Opéra',
                'Richelieu - Drouot',
                'Grands Boulevards',
                'Bonne Nouvelle',
                'Strasbourg - Saint-Denis',
                'République',
                'Filles du Calvaire',
                'Saint-Sébastien - Froissart',
                'Chemin Vert',
                'Bastille',
                'Ledru-Rollin',
                'Faidherbe - Chaligny',
                'Reuilly - Diderot',
                'Montgallet',
                'Daumesnil',
                'Michel Bizot',
                'Porte Dorée',
                'Porte de Charenton',
                'Liberté',
                'Charenton - Écoles',
                'École Vétérinaire de Maisons-Alfort',
                'Maisons-Alfort - Stade',
                'Maisons-Alfort - Les Juilliottes',
                'Créteil - L\'Échat',
                'Créteil - Université',
                'Créteil - Préfecture',
                'Pointe du Lac',
            ], range(1, 38)),

            LineFixtures::LINE_9_REFERENCE => array_map(fn($name, $pos) => ['name' => $name, 'position' => $pos], [
                'Pont de Sèvres',
                'Billancourt',
                'Marcel Sembat',
                'Porte de Saint-Cloud',
                'Exelmans',
                'Michel-Ange - Molitor',
                'Michel-Ange - Auteuil',
                'Jasmin',
                'Ranelagh',
                'La Muette',
                'Rue de la Pompe',
                'Trocadéro',
                'Iéna',
                'Alma - Marceau',
                'Franklin D. Roosevelt',
                'Saint-Philippe du Roule',
                'Miromesnil',
                'Saint-Augustin',
                'Havre - Caumartin',
                'Chaussée d\'Antin - La Fayette',
                'Richelieu - Drouot',
                'Grands Boulevards',
                'Bonne Nouvelle',
                'Strasbourg - Saint-Denis',
                'République',
                'Oberkampf',
                'Saint-Ambroise',
                'Voltaire',
                'Charonne',
                'Rue des Boulets',
                'Nation',
                'Buzenval',
                'Maraîchers',
                'Porte de Montreuil',
                'Robespierre',
                'Croix de Chavaux',
                'Mairie de Montreuil',
            ], range(1, 37)),

            LineFixtures::LINE_10_REFERENCE => [
                ['name' => 'Boulogne - Pont de Saint-Cloud', 'position' => 1],
                ['name' => 'Boulogne - Jean Jaurès', 'position' => 2],
                ['name' => 'Michel-Ange - Molitor', 'position' => 3, 'branch' => 'direction'],
                ['name' => 'Chardon-Lagache', 'position' => 4, 'branch' => 'direction'],
                ['name' => 'Mirabeau', 'position' => 5, 'branch' => 'direction'],
                ['name' => 'Porte d\'Auteuil', 'position' => 6, 'branch' => 'retour'],
                ['name' => 'Michel-Ange - Auteuil', 'position' => 7, 'branch' => 'retour'],
                ['name' => 'Église d\'Auteuil', 'position' => 8, 'branch' => 'retour'],
                ['name' => 'Javel - André Citroën', 'position' => 9],
                ['name' => 'Charles Michels', 'position' => 10],
                ['name' => 'Avenue Émile Zola', 'position' => 11],
                ['name' => 'La Motte-Picquet - Grenelle', 'position' => 12],
                ['name' => 'Ségur', 'position' => 13],
                ['name' => 'Duroc', 'position' => 14],
                ['name' => 'Vaneau', 'position' => 15],
                ['name' => 'Sèvres - Babylone', 'position' => 16],
                ['name' => 'Mabillon', 'position' => 17],
                ['name' => 'Odéon', 'position' => 18],
                ['name' => 'Cluny - La Sorbonne', 'position' => 19],
                ['name' => 'Maubert - Mutualité', 'position' => 20],
                ['name' => 'Cardinal Lemoine', 'position' => 21],
                ['name' => 'Jussieu', 'position' => 22],
                ['name' => 'Gare d\'Austerlitz', 'position' => 23],
            ],

            LineFixtures::LINE_11_REFERENCE => array_map(fn($name, $pos) => ['name' => $name, 'position' => $pos], [
                'Châtelet',
                'Hôtel de Ville',
                'Rambuteau',
                'Arts et Métiers',
                'République',
                'Goncourt',
                'Belleville',
                'Pyrénées',
                'Jourdain',
                'Place des Fêtes',
                'Télégraphe',
                'Porte des Lilas',
                'Mairie des Lilas',
                'Serge Gainsbourg',
                'Romainville - Carnot',
                'Montreuil - Hôpital',
                'La Dhuys',
                'Coteaux Beauclair',
                'Rosny - Bois-Perrier'
            ], range(1, 19)),

            LineFixtures::LINE_12_REFERENCE => array_map(fn($name, $pos) => ['name' => $name, 'position' => $pos], [
                'Mairie d\'Aubervilliers',
                'Aimé Césaire',
                'Front Populaire',
                'Porte de la Chapelle',
                'Marx Dormoy',
                'Marcadet - Poissonniers',
                'Jules Joffrin',
                'Lamarck - Caulaincourt',
                'Abbesses',
                'Pigalle',
                'Saint-Georges',
                'Notre-Dame-de-Lorette',
                'Trinité - d\'Estienne d\'Orves',
                'Saint-Lazare',
                'Madeleine',
                'Concorde',
                'Assemblée Nationale',
                'Solférino',
                'Rue du Bac',
                'Sèvres - Babylone',
                'Rennes',
                'Notre-Dame-des-Champs',
                'Montparnasse - Bienvenüe',
                'Falguière',
                'Pasteur',
                'Volontaires',
                'Vaugirard',
                'Convention',
                'Porte de Versailles',
                'Corentin Celton',
                'Mairie d\'Issy',
            ], range(1, 31)),

            LineFixtures::LINE_13_REFERENCE => [
                // Branche Saint-Denis (de Saint-Denis - Université jusqu'à La Fourche)
                ['name' => 'Saint-Denis - Université', 'position' => 1, 'branch' => 'saint-denis'],
                ['name' => 'Basilique de Saint-Denis', 'position' => 2, 'branch' => 'saint-denis'],
                ['name' => 'Saint-Denis - Porte de Paris', 'position' => 3, 'branch' => 'saint-denis'],
                ['name' => 'Carrefour Pleyel', 'position' => 4, 'branch' => 'saint-denis'],
                ['name' => 'Mairie de Saint-Ouen', 'position' => 5, 'branch' => 'saint-denis'],
                ['name' => 'Garibaldi', 'position' => 6, 'branch' => 'saint-denis'],
                ['name' => 'Porte de Saint-Ouen', 'position' => 7, 'branch' => 'saint-denis'],
                ['name' => 'Guy Môquet', 'position' => 8, 'branch' => 'saint-denis'],

                // Branche Asnières (de Gabriel Péri jusqu'à La Fourche)
                ['name' => 'Les Courtilles', 'position' => 1, 'branch' => 'asnieres'],
                ['name' => 'Les Agnettes', 'position' => 2, 'branch' => 'asnieres'],
                ['name' => 'Gabriel Péri', 'position' => 3, 'branch' => 'asnieres'],
                ['name' => 'Mairie de Clichy', 'position' => 4, 'branch' => 'asnieres'],
                ['name' => 'Porte de Clichy', 'position' => 5, 'branch' => 'asnieres'],
                ['name' => 'Brochant', 'position' => 6, 'branch' => 'asnieres'],

                // Tronc principal (de La Fourche jusqu'à Châtillon - Montrouge)
                ['name' => 'La Fourche', 'position' => 9, 'branch' => 'fork'],
                ['name' => 'Place de Clichy', 'position' => 10],
                ['name' => 'Liège', 'position' => 11],
                ['name' => 'Saint-Lazare', 'position' => 12],
                ['name' => 'Miromesnil', 'position' => 13],
                ['name' => 'Champs-Élysées - Clemenceau', 'position' => 14],
                ['name' => 'Invalides', 'position' => 15],
                ['name' => 'Varenne', 'position' => 16],
                ['name' => 'Saint-François-Xavier', 'position' => 17],
                ['name' => 'Duroc', 'position' => 18],
                ['name' => 'Montparnasse - Bienvenüe', 'position' => 19],
                ['name' => 'Gaîté', 'position' => 20],
                ['name' => 'Pernety', 'position' => 21],
                ['name' => 'Plaisance', 'position' => 22],
                ['name' => 'Porte de Vanves', 'position' => 23],
                ['name' => 'Malakoff - Plateau de Vanves', 'position' => 24],
                ['name' => 'Malakoff - Rue Étienne Dolet', 'position' => 25],
                ['name' => 'Châtillon - Montrouge', 'position' => 26],
            ],

            LineFixtures::LINE_14_REFERENCE => array_map(fn($name, $pos) => ['name' => $name, 'position' => $pos], [
                'Saint-Denis Pleyel',
                'Mairie de Saint-Ouen',
                'Saint-Ouen',
                'Porte de Clichy',
                'Pont Cardinet',
                'Saint-Lazare',
                'Madeleine',
                'Pyramides',
                'Châtelet',
                'Gare de Lyon',
                'Bercy',
                'Cour Saint-Émilion',
                'Bibliothèque François Mitterrand',
                'Olympiades',
                'Maison Blanche',
                'Hôpital Bicêtre',
                'Villejuif - Gustave Roussy',
                'L\'Haÿ-les-Roses',
                'Chevilly-Larue',
                'Thiais - Orly',
                'Aéroport d\'Orly',
            ], range(1, 21)),
        ];
    }

    public function getDependencies(): array
    {
        return [
            LineFixtures::class,
        ];
    }
}
